[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "prague"
optimizer = true
optimizer_runs = 10000
network = "arc"
ffi = true
fs_permissions = [{ access = "read", path = "./test/fixtures" }]

[rpc_endpoints]
arc = "https://rpc.mainnet.arc.io"

[lint]
lint_on_build = false
