#!/usr/bin/env node
// Copies contract ABIs and the mainnet deployment into the web app.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { root, artifact } from './lib.mjs';

const abis = {
  vaultAbi: artifact('LeashVault').abi,
  factoryAbi: artifact('LeashFactory').abi,
};
let out = '// Generated by tools/export-web.mjs. Do not edit.\n';
for (const [name, abi] of Object.entries(abis)) {
  out += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
writeFileSync(join(root, 'web/src/abi.ts'), out);

const depFile = join(root, `deployments/${process.env.DEPLOYMENT ?? '5042'}.json`);
const dep = existsSync(depFile) ? JSON.parse(readFileSync(depFile, 'utf8')) : {};
const deployment = {
  factory: dep.factory ?? null,
  factoryBlock: dep.factoryBlock ?? null,
  demoVault: dep.vault ?? null,
  demoAgent: dep.agent ?? null,
  txs: dep.txs ?? {},
};
writeFileSync(
  join(root, 'web/src/deployment.ts'),
  `// Generated by tools/export-web.mjs. Do not edit.\nexport const deployment = ${JSON.stringify(deployment, null, 2)} as {\n  factory: \`0x\${string}\` | null;\n  factoryBlock: number | null;\n  demoVault: \`0x\${string}\` | null;\n  demoAgent: \`0x\${string}\` | null;\n  txs: Record<string, \`0x\${string}\`>;\n};\n`,
);
console.log('exported abi.ts and deployment.ts', deployment.factory ?? '(no mainnet deployment yet)');
