// Generated by tools/export-web.mjs. Do not edit.
export const deployment = {
  "factory": null,
  "factoryBlock": null,
  "demoVault": null,
  "demoAgent": null,
  "txs": {}
} as {
  factory: `0x${string}` | null;
  factoryBlock: number | null;
  demoVault: `0x${string}` | null;
  demoAgent: `0x${string}` | null;
  txs: Record<string, `0x${string}`>;
};
